FROM node:lts-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache openssl bash

RUN npm install -g bun

COPY package*.json bun.lockb* ./

COPY prisma ./prisma/

RUN bun install

COPY . .

EXPOSE 8000
