# Imagen oficial de Node.js 22.18
FROM node:22.18.0

# Instalar dependencias necesarias y Bun
RUN npm i -g bun

# Directorio de la aplicación
WORKDIR /usr/src/app

# Copiar package.json y bun.lockb (si existe)
COPY package*.json bun.lockb* ./

# Instalar dependencias con Bun (más rápido que npm)
RUN bun install

# Copiar todo el código del proyecto
COPY . .

# Exponer el puerto de la app
EXPOSE 8000
